### ISSUE TITLE
Wakatime API key visible in the config file

### ISSUE THREAD

**Issue by d2s** [ronilaukkarinen/atom-settings#1]
Noticed that there is API key for [Wakatime](https://wakatime.com/) visible in the configuration.

On the file [`config.cson`](https://github.com/ronilaukkarinen/atom-settings/blob/master/config.cson#L23) in line 23:

```
  wakatime:
    apikey: "…"
```

_Risk factor:_
- Someone else could either push new data, or download your usage data (including exact file names and timestamps etc.) from your Wakatime account with it.

_How to fix:_
- Generate new API key from [Wakatime Settings](https://wakatime.com/settings) page.
- Avoid committing private API key to the public GitHub repository.

**Comment by rollecode** [comment]
Oh my. Thanks for letting me know! Yeah I know you never should push passwords or keys to version control, just didn't realize this plugin saves the key to the config file directly. I see [this is already reported](https://github.com/wakatime/atom-wakatime/issues/26).
